package com.javen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourse<M extends BaseCourse<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}

	public java.lang.String getToken() {
		return getStr("token");
	}

	public M setCourseId(java.lang.String courseId) {
		set("courseId", courseId);
		return (M)this;
	}

	public java.lang.String getCourseId() {
		return getStr("courseId");
	}

	public M setCourseName(java.lang.String courseName) {
		set("courseName", courseName);
		return (M)this;
	}

	public java.lang.String getCourseName() {
		return getStr("courseName");
	}

	public M setTeacherName(java.lang.String teacherName) {
		set("teacherName", teacherName);
		return (M)this;
	}

	public java.lang.String getTeacherName() {
		return getStr("teacherName");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}

	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setPrice(java.lang.Float price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Float getPrice() {
		return getFloat("price");
	}

	public M setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
		return (M)this;
	}

	public java.lang.String getIntroduce() {
		return getStr("introduce");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setOnLineTime(java.util.Date onLineTime) {
		set("onLineTime", onLineTime);
		return (M)this;
	}

	public java.util.Date getOnLineTime() {
		return get("onLineTime");
	}

	public M setCourseLogo(java.lang.String courseLogo) {
		set("courseLogo", courseLogo);
		return (M)this;
	}

	public java.lang.String getCourseLogo() {
		return getStr("courseLogo");
	}

	public M setIcon1(java.lang.String icon1) {
		set("icon1", icon1);
		return (M)this;
	}

	public java.lang.String getIcon1() {
		return getStr("icon1");
	}

	public M setIcon2(java.lang.String icon2) {
		set("icon2", icon2);
		return (M)this;
	}

	public java.lang.String getIcon2() {
		return getStr("icon2");
	}

	public M setIcon3(java.lang.String icon3) {
		set("icon3", icon3);
		return (M)this;
	}

	public java.lang.String getIcon3() {
		return getStr("icon3");
	}

	public M setTm(java.lang.String tm) {
		set("tm", tm);
		return (M)this;
	}

	public java.lang.String getTm() {
		return getStr("tm");
	}

	public M setDetail(java.lang.String detail) {
		set("detail", detail);
		return (M)this;
	}

	public java.lang.String getDetail() {
		return getStr("detail");
	}

	public M setCourseType(java.lang.Integer courseType) {
		set("courseType", courseType);
		return (M)this;
	}

	public java.lang.Integer getCourseType() {
		return getInt("courseType");
	}

	public M setCouresTime(java.lang.String couresTime) {
		set("couresTime", couresTime);
		return (M)this;
	}

	public java.lang.String getCouresTime() {
		return getStr("couresTime");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
