package com.javen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUsers<M extends BaseUsers<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOpenId(java.lang.String openId) {
		set("openId", openId);
		return (M)this;
	}

	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	public M setSubscribeTime(java.util.Date subscribeTime) {
		set("subscribeTime", subscribeTime);
		return (M)this;
	}

	public java.util.Date getSubscribeTime() {
		return get("subscribeTime");
	}

	public M setUnsubscribeTime(java.util.Date unsubscribeTime) {
		set("unsubscribeTime", unsubscribeTime);
		return (M)this;
	}

	public java.util.Date getUnsubscribeTime() {
		return get("unsubscribeTime");
	}

	public M setNickName(java.lang.String nickName) {
		set("nickName", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return getStr("nickName");
	}

	public M setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
		return (M)this;
	}

	public java.lang.String getUnionid() {
		return getStr("unionid");
	}

	public M setPrivilege(java.lang.String privilege) {
		set("privilege", privilege);
		return (M)this;
	}

	public java.lang.String getPrivilege() {
		return getStr("privilege");
	}

	public M setHeadimgurl(java.lang.String headimgurl) {
		set("headimgurl", headimgurl);
		return (M)this;
	}

	public java.lang.String getHeadimgurl() {
		return getStr("headimgurl");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}

	public java.lang.String getCountry() {
		return getStr("country");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
