package com.javen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStock<M extends BaseStock<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCourseId(java.lang.Integer courseId) {
		set("courseId", courseId);
		return (M)this;
	}

	public java.lang.Integer getCourseId() {
		return getInt("courseId");
	}

	public M setStockCount(java.lang.Integer stockCount) {
		set("stockCount", stockCount);
		return (M)this;
	}

	public java.lang.Integer getStockCount() {
		return getInt("stockCount");
	}

}
