package com.javen.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("course", "id", Course.class);
		arp.addMapping("idea", "id", Idea.class);
		arp.addMapping("orders", "id", Orders.class);
		arp.addMapping("stock", "id", Stock.class);
		arp.addMapping("tuser", "id", TUser.class);
		arp.addMapping("user_info", "user_no", UserInfo.class);
		arp.addMapping("users", "id", Users.class);
	}
}

